name: dataeng_zc
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - pgcli
    - psycopg-binary
    - psycopg2-binary
    - sqlalchemy
    - notebook
    - pyarrow
    - google-cloud-storage
    # workshop data ingestion
    # - dlt[duckdb]
    - pyspark==3.3.3
    # kafka module
    - kafka-python
    - confluent-kafka
    - requests
    - avro
    - fastavro
    - faust-streaming